### ISSUE TITLE
Zeus Design Call #13

### ISSUE THREAD

**Issue by kaloudis** [BitcoinDesign/Meta#131]
```yaml
Date: 2021-08-11
Time: 8:45am
Timezone: EDT
Duration: 1h
UTCTime: 2021-08-11 12:45 UTC
```

This call is part of the Bitcoin Design community collaboration with Zeus.

Keep up to date with the latest design developments with Zeus on our Figma. If you would like to discuss anything, post a comment below and we may put it on the agenda to cover.

### Time

https://everytimezone.com/s/35e1cff3

### Join the call

https://meet.jit.si/bitcoindesign

### Agenda

- Dev update from Evan
- Branding update from Stephan
- Website update from Tiana
- Wallet update from Bosch

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).
